.PHONY: clean All

All:
	@echo "----------Building project:[ Montella - Debug ]----------"
	@"$(MAKE)" -f  "Montella.mk"
clean:
	@echo "----------Cleaning project:[ Montella - Debug ]----------"
	@"$(MAKE)" -f  "Montella.mk" clean
